{
 "title": "Text-Analyzer",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  { "title": "Text Summary Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Count of Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT current_missing_count, \"timestamp\", reference_missing_count FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Text Length Mean",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_text_length_mean, reference_text_length_mean FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Non Letter Character (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT current_non_letter_char_mean, reference_non_letter_char_mean, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Out-Of-Vocabulary Words (OOV %)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_oov_mean, reference_oov_mean FROM metrics LIMIT 50 "
    }
   ]
  },
  { "title": "Drift Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Drift Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT non_letter_char_drift_score, oov_drift_score, text_length_drift_score, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Accuracy Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_accuracy_score, reference_accuracy_score FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "F1 Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_f1_score, reference_f1_score FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Precision Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_precision_score, reference_precision_score FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Recall Scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", current_recall_score, reference_recall_score FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}